### ISSUE TITLE
Invalid Host header when change to "Host:0.0.0.0" 

### ISSUE THREAD

**Issue by entaku19890818** [callemall/material-ui-webpack-example#10]
I rewritten the following host so that it can be accessed from other clients
`` `
Host: '0.0.0.0'
`` `

Execute as usual.
`Npm start`

I accessing the web server that the following message is displayed.

`` `
Invalid Host header
`` `

Do you know the cause?

**Comment by oliviertassinari** [comment]
Have a look at https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a
