### ISSUE TITLE
ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js

### ISSUE THREAD

**Issue by ikzjfr0** [callemall/material-ui-webpack-example#12]
I followed your instructions and got following error when trying to run "npm start"

```
ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/ViewportMetrics' in /Users/liangwang/Downloads/material-ui-webpack-example-25938ac6f5db94645e6ea9f24a903792d3133c5d/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-58
```

**Comment by qwe852** [comment]
I got the same problem too.
change dependencies version will fix the problem
package.json 

  "dependencies": {
    "material-ui": "^0.16.3",
    "react": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-tap-event-plugin": "^2.0.0"
  }

**Comment by oliviertassinari** [comment]
It's an external dependency issue. Let's hope that they have published new releases fixing the issue. I'm closing the issue for now.
