### ISSUE TITLE
[docs] Example needs to be updated to support 'v1-alpha' branch of material-ui.

### ISSUE THREAD

**Issue by akshaynaik404** [callemall/material-ui-webpack-example#14]

**Comment by oliviertassinari** [comment]
True, I think that we should delete the repositories projects and move them to the main repository. One example with create react app and next.js should be enough. We already have one with next.js on their repository so it's just a matter of linking it in a new README.

**Comment by oliviertassinari** [comment]
Do you want to take care of it? :)

**Comment by akshaynaik404** [comment]
Sure. I will create a demo and share it with you here.

Mind you though, I am not that good at React or Material-UI for that matter!

I will try to replicate the current example.

**Comment by oliviertassinari** [comment]
Here is the next.js example https://github.com/zeit/next.js/blob/v3-beta/examples/with-material-ui-next/README.md
We can do the same with [create-react-app](https://github.com/facebookincubator/create-react-app). You can directly submit a PR on the main repository on the v1-alpha branch. We will close this one and [material-ui-browserify-gulp-example](https://github.com/callemall/material-ui-browserify-gulp-example) once we are good :).

**Comment by akshaynaik404** [comment]
We can close this issue now as [#7485](https://github.com/callemall/material-ui/pull/7485) has been merged.
