### ISSUE TITLE
not support ES6 Arrow Function

### ISSUE THREAD

**Issue by cbyniiaii** [callemall/material-ui-webpack-example#2]
`class Main extends Component {
  abc = () => {
    alert("abc");
  }`

**I get the this Error**
ERROR in ./src/app/Main.js
Module build failed: SyntaxError: Unexpected token (38:6)

>36 |   }
  37 | 
 38 |   abc = () => {
                   ^
39 |     alert("abc");
  40 |   }
  41 |

**Comment by oliviertassinari** [comment]
I agree, it would be great to add the `stage-2` babel preset in order for out docs examples to work with this webpack example boilerplate 👍 .
