### ISSUE TITLE
In the example Case no longer icon

### ISSUE THREAD

**Issue by mattmengSemioe** [callemall/material-ui-webpack-example#4]
why

**Comment by lucasbento** [comment]
@mattmengSemioe: we are not using icons in this example, do you mean that you can't use Material UI's icons?

**Comment by mattmengSemioe** [comment]
ah Then how can I get use those ICONS

**Comment by lucasbento** [comment]
@mattmengSemioe: it's specified here: http://www.material-ui.com/#/components/svg-icon.

I'm closing this issue since this is not the place for regular how-to questions, please head over to [stackoverflow](stackoverflow.com).

**Comment by mattmengSemioe** [comment]
thank you
